---
- hosts: all
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
      update_cache: yes
    #when: ansible_facts['os_family'] == "RedHat"
    when: ansible_os_family == "RedHat"
  - name: install apache
    apt:
      name: apache2
      state: present
      update_cache: yes
    #when: ansible_facts['os_family'] == "Debian"
    when: ansible_os_family == "Debian"
