---
- hosts: ubuntu
  become: yes
  tasks: 
  - name: install apache2 pkg in ubuntu machines
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: stop the service 
    service:
      name: apache2
      state: started


    
