---
- hosts: centos
  become: yes
  tasks:
  - name: install httpd in centos machine
    yum:
      name: httpd
      state: present
  - name: ensure service is running
    service:
      name: httpd
      state: started
      enabled: yes
