---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: this is to copy a file from ansible server to client machines
    copy:
      src: /home/ansible/file/test/handler.txt
      dest: /home/ansible/1234.txt
      owner: ansible
      group: ansible
      mode: '0777'

