---
- hosts: freepbx
  become: yes
  gather_facts: no
  tasks:
    - name: download a file using get_url module
      get_url:
        url: http://mirror.freepbx.org/freepbx-2.11.0.42.tgz
        dest: /home/ansible/freepbx.tgz
        mode: '0744'

