---
- hosts: ubuntu
  become: yes
  tasks:
  - name: this is install apache2 for ubuntu hosts
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: Check the service
    service:
      name: apache2
      state: started
