---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2 based on OS
    apt:
      name: apache2
      state: present
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"
  - name: install httpd based on OS
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"   

